[DataBase]
Type     = ""
User     = ""
Password = ""
Host     = ""
Port     = 3306
BDName   = ""


[Redis]
Address = "localhost:6379"
Password = ""


[Minio]
Endpoint        = "minio.endpoint"
AccessKeyID     = "minio.accesskey"
SecretAccessKey = "minio.secretaccesskey"
UseSSL          = true