[DataBase]
DSN = "databse dsn"


[Redis]
Address = "redis-19441.c295.ap-southeast-1-1.ec2.cloud.redislabs.com:19441"
Password = "rqOYjdbbvIbat4rVAmp0f64oBLJVLpdv"


[Minio]
Endpoint        = "play.min.io"
AccessKeyID     = "Q3AM3UQ867SPQQA43P2F"
SecretAccessKey = "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
UseSSL          = true

[Develop]
DevMod = true