[DataBase] #数据库
Type     = ""
User     = ""
Password = ""
Host     = ""
Port     = 3306
BDName   = ""


[Redis]
Address = ""  # Redis 连接
Password = "" # 没有密码则为空


[Minio]
Endpoint        = "play.min.io" # Minio #连接地址
AccessKeyID     = "Q3AM3UQ867A43P2F"
SecretAccessKey = "zuf+tfteSlswRLbZam1KYY3TG"
UseSSL          = true #是否启用SSL

[Develop]
DevMod = true  # 是否启用开发模式