@startuml
skinparam responseMessageBelowArrow true
participant 主客户端   as client
control     服务器     as server
entity      同步器   as  sync
database    数据库     as  db
database    对象存储    as store



@enduml