[DataBase]
Type     = "mysql"
User     = "root"
Password = "zylzyl233"
Host     = "127.0.0.1"
Port     = 3306
BDName   = "testdatabase"


[Redis]
Address = "localhost:6379"
Password = ""


[Minio]
Endpoint        = "minio.endpoint"
AccessKeyID     = "minio.accesskey"
SecretAccessKey = "minio.secretaccesskey"
UseSSL          = true