[DataBase]
Type     = "mysql"
User     = "root"
Password = "zylzyl233"
Host     = "127.0.0.1"
Port     = 3306
BDName   = "testdatabase"


[Redis]
Address = "localhost:6379"
Password = ""


[Minio]
Endpoint        = "localhost:9001"
AccessKeyID     = "qzMJRjDS3bf80pxtlcwh"
SecretAccessKey = "Efyn8NrsTzyX6l2mfHvasMP3bQvR8RZxgmLjPl8v"
UseSSL          = false