// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fsm/pkg/ent/schema"
	"fsm/pkg/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPassWord is the schema descriptor for pass_word field.
	userDescPassWord := userFields[2].Descriptor()
	// user.PassWordValidator is a validator for the "pass_word" field. It is called by the builders before save.
	user.PassWordValidator = userDescPassWord.Validators[0].(func(string) error)
	// userDescUserName is the schema descriptor for user_name field.
	userDescUserName := userFields[4].Descriptor()
	// user.UserNameValidator is a validator for the "user_name" field. It is called by the builders before save.
	user.UserNameValidator = userDescUserName.Validators[0].(func(string) error)
}
