// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"fsm/pkg/ent/predicate"
	"fsm/pkg/ent/synctask"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SyncTaskUpdate is the builder for updating SyncTask entities.
type SyncTaskUpdate struct {
	config
	hooks    []Hook
	mutation *SyncTaskMutation
}

// Where appends a list predicates to the SyncTaskUpdate builder.
func (stu *SyncTaskUpdate) Where(ps ...predicate.SyncTask) *SyncTaskUpdate {
	stu.mutation.Where(ps...)
	return stu
}

// SetUserID sets the "user_id" field.
func (stu *SyncTaskUpdate) SetUserID(s string) *SyncTaskUpdate {
	stu.mutation.SetUserID(s)
	return stu
}

// SetType sets the "type" field.
func (stu *SyncTaskUpdate) SetType(s string) *SyncTaskUpdate {
	stu.mutation.SetType(s)
	return stu
}

// SetName sets the "name" field.
func (stu *SyncTaskUpdate) SetName(s string) *SyncTaskUpdate {
	stu.mutation.SetName(s)
	return stu
}

// SetRootDir sets the "root_dir" field.
func (stu *SyncTaskUpdate) SetRootDir(s string) *SyncTaskUpdate {
	stu.mutation.SetRootDir(s)
	return stu
}

// SetDeleted sets the "deleted" field.
func (stu *SyncTaskUpdate) SetDeleted(b bool) *SyncTaskUpdate {
	stu.mutation.SetDeleted(b)
	return stu
}

// SetCreateTime sets the "create_time" field.
func (stu *SyncTaskUpdate) SetCreateTime(t time.Time) *SyncTaskUpdate {
	stu.mutation.SetCreateTime(t)
	return stu
}

// Mutation returns the SyncTaskMutation object of the builder.
func (stu *SyncTaskUpdate) Mutation() *SyncTaskMutation {
	return stu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (stu *SyncTaskUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(stu.hooks) == 0 {
		affected, err = stu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SyncTaskMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			stu.mutation = mutation
			affected, err = stu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(stu.hooks) - 1; i >= 0; i-- {
			if stu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = stu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, stu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (stu *SyncTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := stu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (stu *SyncTaskUpdate) Exec(ctx context.Context) error {
	_, err := stu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (stu *SyncTaskUpdate) ExecX(ctx context.Context) {
	if err := stu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (stu *SyncTaskUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   synctask.Table,
			Columns: synctask.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: synctask.FieldID,
			},
		},
	}
	if ps := stu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := stu.mutation.UserID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: synctask.FieldUserID,
		})
	}
	if value, ok := stu.mutation.GetType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: synctask.FieldType,
		})
	}
	if value, ok := stu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: synctask.FieldName,
		})
	}
	if value, ok := stu.mutation.RootDir(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: synctask.FieldRootDir,
		})
	}
	if value, ok := stu.mutation.Deleted(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: synctask.FieldDeleted,
		})
	}
	if value, ok := stu.mutation.CreateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: synctask.FieldCreateTime,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, stu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{synctask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// SyncTaskUpdateOne is the builder for updating a single SyncTask entity.
type SyncTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SyncTaskMutation
}

// SetUserID sets the "user_id" field.
func (stuo *SyncTaskUpdateOne) SetUserID(s string) *SyncTaskUpdateOne {
	stuo.mutation.SetUserID(s)
	return stuo
}

// SetType sets the "type" field.
func (stuo *SyncTaskUpdateOne) SetType(s string) *SyncTaskUpdateOne {
	stuo.mutation.SetType(s)
	return stuo
}

// SetName sets the "name" field.
func (stuo *SyncTaskUpdateOne) SetName(s string) *SyncTaskUpdateOne {
	stuo.mutation.SetName(s)
	return stuo
}

// SetRootDir sets the "root_dir" field.
func (stuo *SyncTaskUpdateOne) SetRootDir(s string) *SyncTaskUpdateOne {
	stuo.mutation.SetRootDir(s)
	return stuo
}

// SetDeleted sets the "deleted" field.
func (stuo *SyncTaskUpdateOne) SetDeleted(b bool) *SyncTaskUpdateOne {
	stuo.mutation.SetDeleted(b)
	return stuo
}

// SetCreateTime sets the "create_time" field.
func (stuo *SyncTaskUpdateOne) SetCreateTime(t time.Time) *SyncTaskUpdateOne {
	stuo.mutation.SetCreateTime(t)
	return stuo
}

// Mutation returns the SyncTaskMutation object of the builder.
func (stuo *SyncTaskUpdateOne) Mutation() *SyncTaskMutation {
	return stuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (stuo *SyncTaskUpdateOne) Select(field string, fields ...string) *SyncTaskUpdateOne {
	stuo.fields = append([]string{field}, fields...)
	return stuo
}

// Save executes the query and returns the updated SyncTask entity.
func (stuo *SyncTaskUpdateOne) Save(ctx context.Context) (*SyncTask, error) {
	var (
		err  error
		node *SyncTask
	)
	if len(stuo.hooks) == 0 {
		node, err = stuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SyncTaskMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			stuo.mutation = mutation
			node, err = stuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(stuo.hooks) - 1; i >= 0; i-- {
			if stuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = stuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, stuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*SyncTask)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from SyncTaskMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (stuo *SyncTaskUpdateOne) SaveX(ctx context.Context) *SyncTask {
	node, err := stuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (stuo *SyncTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := stuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (stuo *SyncTaskUpdateOne) ExecX(ctx context.Context) {
	if err := stuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (stuo *SyncTaskUpdateOne) sqlSave(ctx context.Context) (_node *SyncTask, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   synctask.Table,
			Columns: synctask.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: synctask.FieldID,
			},
		},
	}
	id, ok := stuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SyncTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := stuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, synctask.FieldID)
		for _, f := range fields {
			if !synctask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != synctask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := stuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := stuo.mutation.UserID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: synctask.FieldUserID,
		})
	}
	if value, ok := stuo.mutation.GetType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: synctask.FieldType,
		})
	}
	if value, ok := stuo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: synctask.FieldName,
		})
	}
	if value, ok := stuo.mutation.RootDir(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: synctask.FieldRootDir,
		})
	}
	if value, ok := stuo.mutation.Deleted(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: synctask.FieldDeleted,
		})
	}
	if value, ok := stuo.mutation.CreateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: synctask.FieldCreateTime,
		})
	}
	_node = &SyncTask{config: stuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, stuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{synctask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
